/** Fun "Did you know?" facts shown while the AI is thinking. */
export const FACTS: string[] = [
  'The first computer programmer was Ada Lovelace — she wrote code in 1843, before computers even existed!',
  'The word "bug" in computers comes from a real moth that got stuck inside an early computer in 1947.',
  'Minecraft was made by just ONE person — Markus "Notch" Persson — in his spare time!',
  'The first video game, Pong, was made in 1972 and was just two paddles and a ball.',
  'There are more than 700 different programming languages in the world.',
  'The @ symbol used in email addresses is over 500 years old!',
  'YouTube was invented by three people who used to work at PayPal.',
  'The first iPhone had no App Store — it launched with only Apple\'s built-in apps.',
  'Google was started in a garage by two Stanford students in 1998.',
  'The first computer mouse was made of wood!',
  'A standard computer can do more calculations per second than all humans on Earth combined.',
  'The emoji 😂 (Face with Tears of Joy) was the most-used emoji for years in a row.',
  'Roblox was created by one person, David Baszucki, who wanted kids to build virtual worlds.',
  'The word "computer" used to describe a human whose job was to do math calculations.',
  'Pac-Man was designed to be fun for everyone — the creator wanted even people who hated games to enjoy it.',
  'The internet has more than 1.5 billion websites, but most people only visit a tiny fraction of them.',
  'The first mobile phone call was made in 1973, and the phone weighed over 2 pounds!',
  'Instagram was bought by Facebook for $1 billion — and it only had 13 employees at the time!',
  'Angry Birds was Rovio\'s 52nd game — all their previous games failed!',
  'The original Nintendo GameBoy had less computing power than a digital watch does today.',
  'HTML, the language used to build websites, was invented in 1991.',
  'The creator of Flappy Bird deleted the game because it was TOO popular and was taking over his life.',
  'Amazon started as an online bookstore before selling anything else.',
  'Wikipedia is written by volunteers — regular people who share what they know for free.',
  'The first text message ever sent said: "Merry Christmas."',
  'Snapchat was originally called "Picaboo" before the name was changed.',
  'The space shuttle used software that was 40 years old — because it worked perfectly and nobody wanted to risk changing it.',
  'There are about 3 billion gamers in the world — that\'s almost half of all people on Earth!',
  'The creator of Super Mario, Shigeru Miyamoto, also created Donkey Kong, The Legend of Zelda, and Pikmin.',
  'Python, a popular programming language, is named after Monty Python\'s Flying Circus — not the snake!',
  'The first tweet ever sent said: "just setting up my twttr."',
  'TikTok is used in over 150 countries and has more than 1 billion users.',
  'The code that runs most of the internet is written and maintained for FREE by volunteers.',
  'Email is older than the internet — the first email was sent in 1971.',
  'The average person unlocks their phone 96 times per day.',
  'A Wi-Fi signal can travel through walls because it uses radio waves, just like a radio.',
  'The first computer virus was created in 1983 by a student as an experiment.',
  'Scratch, a coding tool made for kids, has more than 100 million projects created by kids like you!',
  'JavaScript was written in just 10 days by one person at Netscape in 1995.',
  'The pound sign (#) on your keyboard is called an "octothorpe."',
  'The moon landing computers had less memory than a USB stick you can buy for $1 today.',
  'WhatsApp sends over 100 billion messages every single day.',
  'The QWERTY keyboard layout was designed in 1878 to stop typewriters from jamming.',
  'The first computer game ever made was called "Tennis for Two" — it just showed a tennis court from the side.',
  'Netflix started as a DVD-by-mail service before becoming a streaming platform.',
  'The hashtag # was first used on Twitter in 2007 to group conversations by topic.',
  'Over 500 hours of video are uploaded to YouTube every single minute.',
  'The first website is still live today — it explains what the World Wide Web is.',
  'A Chromebook does most of its work in the cloud, which means it works even with a slow processor.',
  'The creator of Minecraft sold it to Microsoft for $2.5 billion — that\'s $2,500,000,000!',
  '"Hello, World!" is the first program almost every programmer writes when learning a new language.',
  'The blue light from screens tells your brain it\'s daytime — that\'s why screens can keep you awake.',
  'The first Apple computer was sold for $666.66 in 1976.',
  'A QR code can hold up to 7,089 numbers or 4,296 letters of information.',
  'Coding is now a required subject in schools in over 20 countries around the world.',
  'The game Among Us was barely popular for two years — then it suddenly had 500 million players!',
  'Most professional programmers look up answers online — you\'re supposed to! It\'s not cheating.',
  'The word "pixel" comes from "picture element" — each tiny dot on your screen is one pixel.',
  'There are more transistors in your smartphone than there are stars in the Milky Way galaxy.',
  'The first ever computer programmer was a woman, and the first computer bug was found by a woman, too!',
  'Coding is sometimes called the "new literacy" — like reading and writing for the digital world.',
]

/** Pick a random fact, avoiding the last one shown */
export function getRandomFact(lastFact?: string): string {
  const pool = FACTS.filter((f) => f !== lastFact)
  return pool[Math.floor(Math.random() * pool.length)]
}
